Greeting.create(id: 1, message: 'Hi!')
Greeting.create(id: 2, message: 'Hello!')
Greeting.create(id: 3, message: 'Good morning')
Greeting.create(id: 4, message: 'Good evening')
Greeting.create(id: 5, message: 'Good afternoon')